### ISSUE TITLE
Is this the same effects of rx_disposeBag?

### ISSUE THREAD

**Issue by frogcjn** [RxSwiftCommunity/NSObject-Rx#17] opened 2016-03-20 05:33 UTC
`````` swift
some_rx_task
     .take_until(rx_delloc)
     ....

```swift
some_rx_task
     ...
     .addDisposeTo(rx)disposeBag
``````

**Comment by ashfurrow** [comment] 2016-03-21 15:01
Closing as a duplicate of #18, commented there.

**Closed as completed by ashfurrow** 2016-03-21 15:01 UTC
